(defn my-cfg1 (target & opts)
  (let* ((fmt (if (empty? opts) :mermaid (first opts)))
         (cfg (fn/flow target)))
    (when (nil? cfg)
      (error [:type-error "no LIR"]))
    (cond
      ((= fmt :mermaid) (fn/cfg-mermaid cfg))
      ((= fmt :dot)     (fn/cfg-dot cfg))
      (true (error [:type-error "unknown format"])))))

(defn f1 () 1)

(display (type (my-cfg1 f1))) (display "\n")
(display (type (my-cfg1 f1))) (display "\n")
(display (type (my-cfg1 f1))) (display "\n")
(display (type (my-cfg1 f1))) (display "\n")
(display (type (my-cfg1 f1))) (display "\n")
(display (type (my-cfg1 f1))) (display "\n")
(display (type (my-cfg1 f1))) (display "\n")
(display (type (my-cfg1 f1))) (display "\n")
(display (type (my-cfg1 f1))) (display "\n")
(display (type (my-cfg1 f1))) (display "\n")
(display (type (my-cfg1 f1))) (display "\n")
(display (type (my-cfg1 f1))) (display "\n")
