(defn complex-func (x)
  (letrec ((helper (fn (s)
             (-> s
               (string/replace "a" "b")
               (string/replace "c" "d")))))
    (helper (string x))))

(display (complex-func 1)) (display "\n")
(display (complex-func 2)) (display "\n")
(display (complex-func 3)) (display "\n")
(display (complex-func 4)) (display "\n")
(display (complex-func 5)) (display "\n")
(display (complex-func 6)) (display "\n")
(display (complex-func 7)) (display "\n")
(display (complex-func 8)) (display "\n")
(display (complex-func 9)) (display "\n")
(display (complex-func 10)) (display "\n")
(display (complex-func 11)) (display "\n")
(display (complex-func 12)) (display "\n")
