(defn my-func (x)
  (let* ((a (+ x 1))
         (b (* a 2)))
    (string b)))

(display (my-func 1)) (display "\n")
(display (my-func 2)) (display "\n")
(display (my-func 3)) (display "\n")
(display (my-func 4)) (display "\n")
(display (my-func 5)) (display "\n")
(display (my-func 6)) (display "\n")
(display (my-func 7)) (display "\n")
(display (my-func 8)) (display "\n")
(display (my-func 9)) (display "\n")
(display (my-func 10)) (display "\n")
(display (my-func 11)) (display "\n")
(display (my-func 12)) (display "\n")
