(defn f1 () 1)

(display (type (fn/cfg f1))) (display "\n")
(display (type (fn/cfg f1))) (display "\n")
(display (type (fn/cfg f1))) (display "\n")
(display (type (fn/cfg f1))) (display "\n")
(display (type (fn/cfg f1))) (display "\n")
(display (type (fn/cfg f1))) (display "\n")
(display (type (fn/cfg f1))) (display "\n")
(display (type (fn/cfg f1))) (display "\n")
(display (type (fn/cfg f1))) (display "\n")
(display (type (fn/cfg f1))) (display "\n")
(display (type (fn/cfg f1))) (display "\n")
(display (type (fn/cfg f1))) (display "\n")
