(defn f1 () 1)
(defn f2 () 2)
(defn f3 () 3)
(defn f4 () 4)
(defn f5 () 5)
(defn f6 () 6)
(defn f7 () 7)
(defn f8 () 8)
(defn f9 () 9)
(defn f10 () 10)

(display "r1: ")
(display (type (fn/cfg-mermaid (fn/flow f1))))
(display "\n")
(display "r2: ")
(display (type (fn/cfg-mermaid (fn/flow f2))))
(display "\n")
(display "r3: ")
(display (type (fn/cfg-mermaid (fn/flow f3))))
(display "\n")
(display "r4: ")
(display (type (fn/cfg-mermaid (fn/flow f4))))
(display "\n")
(display "r5: ")
(display (type (fn/cfg-mermaid (fn/flow f5))))
(display "\n")
(display "r6: ")
(display (type (fn/cfg-mermaid (fn/flow f6))))
(display "\n")
(display "r7: ")
(display (type (fn/cfg-mermaid (fn/flow f7))))
(display "\n")
(display "r8: ")
(display (type (fn/cfg-mermaid (fn/flow f8))))
(display "\n")
(display "r9: ")
(display (type (fn/cfg-mermaid (fn/flow f9))))
(display "\n")
(display "r10: ")
(display (type (fn/cfg-mermaid (fn/flow f10))))
(display "\n")
(display "r11: ")
(display (type (fn/cfg-mermaid (fn/flow f1))))
(display "\n")
(display "r12: ")
(display (type (fn/cfg-mermaid (fn/flow f2))))
(display "\n")
