(defn my-cfg-no-var (target)
  (let* ((cfg (fn/flow target)))
    (when (nil? cfg)
      (error [:type-error "no LIR"]))
    (fn/cfg-mermaid cfg)))

(defn f1 () 1)

(display (type (my-cfg-no-var f1))) (display "\n")
(display (type (my-cfg-no-var f1))) (display "\n")
(display (type (my-cfg-no-var f1))) (display "\n")
(display (type (my-cfg-no-var f1))) (display "\n")
(display (type (my-cfg-no-var f1))) (display "\n")
(display (type (my-cfg-no-var f1))) (display "\n")
(display (type (my-cfg-no-var f1))) (display "\n")
(display (type (my-cfg-no-var f1))) (display "\n")
(display (type (my-cfg-no-var f1))) (display "\n")
(display (type (my-cfg-no-var f1))) (display "\n")
(display (type (my-cfg-no-var f1))) (display "\n")
(display (type (my-cfg-no-var f1))) (display "\n")
