(defn complex-func2 (x)
  (let* ((s (string x))
         (a (string/replace s "1" "one"))
         (b (string/replace a "2" "two"))
         (c (append "result: " b)))
    c))

(display (complex-func2 1)) (display "\n")
(display (complex-func2 2)) (display "\n")
(display (complex-func2 3)) (display "\n")
(display (complex-func2 4)) (display "\n")
(display (complex-func2 5)) (display "\n")
(display (complex-func2 6)) (display "\n")
(display (complex-func2 7)) (display "\n")
(display (complex-func2 8)) (display "\n")
(display (complex-func2 9)) (display "\n")
(display (complex-func2 10)) (display "\n")
(display (complex-func2 11)) (display "\n")
(display (complex-func2 12)) (display "\n")
