(defn f1 () 1)
(defn f2 () 2)
(defn f3 () 3)
(defn f4 () 4)
(defn f5 () 5)
(defn f6 () 6)
(defn f7 () 7)
(defn f8 () 8)
(defn f9 () 9)
(defn f10 () 10)

# Make 9 fn/cfg calls first
(fn/cfg f1)
(fn/cfg f2)
(fn/cfg f3)
(fn/cfg f4)
(fn/cfg f5)
(fn/cfg f6)
(fn/cfg f7)
(fn/cfg f8)
(fn/cfg f9)

# Now call fn/cfg-mermaid directly (bypassing fn/cfg)
(def cfg-data (fn/flow f10))
(display "cfg-data type: ")
(display (type cfg-data))
(display "\n")

# Try calling fn/cfg-mermaid directly
(display "Calling fn/cfg-mermaid directly...\n")
(def mermaid-result (fn/cfg-mermaid cfg-data))
(display "mermaid result type: ")
(display (type mermaid-result))
(display "\n")
