(defn test-var2 (x & rest)
  (let* ((fmt (if (empty? rest) :default (first rest)))
         (result (string x)))
    (cond
      ((= fmt :default) (append "default: " result))
      ((= fmt :other) (append "other: " result))
      (true (append "unknown: " result)))))

(display (test-var2 1)) (display "\n")
(display (test-var2 2)) (display "\n")
(display (test-var2 3)) (display "\n")
(display (test-var2 4)) (display "\n")
(display (test-var2 5)) (display "\n")
(display (test-var2 6)) (display "\n")
(display (test-var2 7)) (display "\n")
(display (test-var2 8)) (display "\n")
(display (test-var2 9)) (display "\n")
(display (test-var2 10)) (display "\n")
(display (test-var2 11)) (display "\n")
(display (test-var2 12)) (display "\n")
