(defn test-var (x & rest)
  (display "x=") (display x) (display " rest-type=") (display (type rest)) (display " nil?=") (display (nil? rest)) (display " empty?=")
  (if (nil? rest) (display "SKIP") (display (empty? rest)))
  (display "\n"))

(test-var 1)
(test-var 2)
(test-var 3)
(test-var 4)
(test-var 5)
(test-var 6)
(test-var 7)
(test-var 8)
(test-var 9)
(test-var 10)
(test-var 11)
(test-var 12)
