// audited: 2026-09-21
//! One opcode byte per `LirInstr` variant.
//!
//! docs/impl/image/measurements.md
//!
//! Its own file because the enum has 88 variants, and the prototype's node
//! carries the variant as a byte: a backend that matches on 88 opcodes
//! branches as the shipped translator does, where a coarser encoding would
//! flatter the read.

use elle::lir::LirInstr;

/// The opcode byte: one per `LirInstr` variant, in declaration order. The match
/// is exhaustive, so a new variant is reported here rather than encoded as
/// something else.
pub fn opcode(i: &LirInstr) -> u8 {
    match i {
        LirInstr::Const { .. } => 0,
        LirInstr::ValueConst { .. } => 1,
        LirInstr::MaterializeConst { .. } => 2,
        LirInstr::LoadLocal { .. } => 3,
        LirInstr::StoreLocal { .. } => 4,
        LirInstr::StoreLocalRefcounted { .. } => 5,
        LirInstr::LoadCapture { .. } => 6,
        LirInstr::LoadCaptureRaw { .. } => 7,
        LirInstr::StoreCapture { .. } => 8,
        LirInstr::MakeClosure { .. } => 9,
        LirInstr::LoadSelf { .. } => 10,
        LirInstr::Call { .. } => 11,
        LirInstr::SuspendingCall { .. } => 12,
        LirInstr::TailCall { .. } => 13,
        LirInstr::List { .. } => 14,
        LirInstr::MakeArrayMut { .. } => 15,
        LirInstr::First { .. } => 16,
        LirInstr::Rest { .. } => 17,
        LirInstr::BinOp { .. } => 18,
        LirInstr::UnaryOp { .. } => 19,
        LirInstr::Convert { .. } => 20,
        LirInstr::Compare { .. } => 21,
        LirInstr::IsNil { .. } => 22,
        LirInstr::IsPair { .. } => 23,
        LirInstr::IsArray { .. } => 24,
        LirInstr::IsArrayMut { .. } => 25,
        LirInstr::IsStruct { .. } => 26,
        LirInstr::IsStructMut { .. } => 27,
        LirInstr::IsSet { .. } => 28,
        LirInstr::IsSetMut { .. } => 29,
        LirInstr::ArrayMutLen { .. } => 30,
        LirInstr::MakeCaptureCell { .. } => 31,
        LirInstr::LoadCaptureCell { .. } => 32,
        LirInstr::StoreCaptureCell { .. } => 33,
        LirInstr::MatchFail { .. } => 34,
        LirInstr::FirstDestructure { .. } => 35,
        LirInstr::RestDestructure { .. } => 36,
        LirInstr::ArrayMutRefDestructure { .. } => 37,
        LirInstr::ArrayMutSliceFrom { .. } => 38,
        LirInstr::StructGetOrNil { .. } => 39,
        LirInstr::StructGetDestructure { .. } => 40,
        LirInstr::StructRest { .. } => 41,
        LirInstr::FirstOrNil { .. } => 42,
        LirInstr::RestOrNil { .. } => 43,
        LirInstr::ArrayMutRefOrNil { .. } => 44,
        LirInstr::LoadResumeValue { .. } => 45,
        LirInstr::Eval { .. } => 46,
        LirInstr::ArrayMutExtend { .. } => 47,
        LirInstr::ArrayMutPush { .. } => 48,
        LirInstr::CallArrayMut { .. } => 49,
        LirInstr::TailCallArrayMut { .. } => 50,
        LirInstr::IncrefRegion { .. } => 51,
        LirInstr::DecrefRegion { .. } => 52,
        LirInstr::DecrefValueRegion { .. } => 53,
        LirInstr::DecrefCellRegion { .. } => 54,
        LirInstr::IncrefValueRegion { .. } => 55,
        LirInstr::AdoptRegion { .. } => 56,
        LirInstr::AdoptCellRegion { .. } => 57,
        LirInstr::FreeRegionGroup { .. } => 58,
        LirInstr::AdoptIntoActivation { .. } => 59,
        LirInstr::AssertRegionMatches { .. } => 60,
        LirInstr::PushParamFrame { .. } => 61,
        LirInstr::PopParamFrame => 62,
        LirInstr::CheckSignalBound { .. } => 63,
        LirInstr::IsEmpty { .. } => 64,
        LirInstr::IsBool { .. } => 65,
        LirInstr::IsInt { .. } => 66,
        LirInstr::IsFloat { .. } => 67,
        LirInstr::IsString { .. } => 68,
        LirInstr::IsKeyword { .. } => 69,
        LirInstr::IsSymbolCheck { .. } => 70,
        LirInstr::IsBytes { .. } => 71,
        LirInstr::IsBox { .. } => 72,
        LirInstr::IsClosure { .. } => 73,
        LirInstr::IsFiber { .. } => 74,
        LirInstr::TypeOf { .. } => 75,
        LirInstr::Length { .. } => 76,
        LirInstr::Get { .. } => 77,
        LirInstr::Put { .. } => 78,
        LirInstr::Del { .. } => 79,
        LirInstr::Has { .. } => 80,
        LirInstr::IntrPush { .. } => 81,
        LirInstr::IntrStringPush { .. } => 82,
        LirInstr::IntrBytesPush { .. } => 83,
        LirInstr::Pop { .. } => 84,
        LirInstr::Freeze { .. } => 85,
        LirInstr::Thaw { .. } => 86,
        LirInstr::Identical { .. } => 87,
    }
}
