// audited: 2026-10-06
//! The keyword vocabulary: every spelling the Rust runtime mints from a fixed
//! string.
//!
//! docs/impl/symbol.md

/// Every keyword spelling the Rust runtime mints from a fixed string —
/// result-struct keys, error kinds, type names, config, trace and event
/// keywords.
/// Display-only: identity never consults this list. Spellings that reach a
/// keyword dynamically (read from source, converted from a string, minted by
/// a plugin, parsed from JSON) are learned by the instance memo instead.
///
/// `vocabulary_is_collision_free` proves the list injective under the hash.
/// A missing entry is a defect with no compile error behind it: the keyword
/// prints as `#<keyword:hash>`, and `json/serialize` refuses any struct that
/// carries it as a key, because JSON has no rendering for a hash. Two tests
/// keep the list complete, since the constructor cannot —
/// `vocabulary_covers_literal_mint_sites` scans every form that hands a
/// literal to a keyword constructor, and `vocabulary_covers_accessor_mint_sites`
/// enumerates the tables whose `&'static str` accessors feed the same
/// constructors from behind a `match` arm or a table no scan can see.
pub(crate) static VOCABULARY: &[&str] = &[
    // Result-struct keys and general fields
    "a",
    "active-allocator",
    "addr",
    "aliases",
    "allocated-bytes",
    "annotated",
    "args",
    "arity",
    "attempts",
    "blocks",
    "calls",
    "category",
    "code",
    "col",
    "constructor",
    "count",
    "cwd",
    "data",
    "doc",
    "edges",
    "entry",
    "env",
    "example",
    "exports",
    "file",
    "first",
    "fn",
    "func",
    "id",
    "input",
    "instrs",
    "k",
    "kind",
    "label",
    "last",
    "length",
    "line",
    "locals",
    "message",
    "name",
    "named",
    "named-keys",
    "none",
    "optional",
    "origin",
    "params",
    "path",
    "peak-count",
    "pid",
    "port",
    "process",
    "rc",
    "reason",
    "region",
    "reports",
    "regs",
    "required",
    "rest",
    "scope-depth",
    "scope-dtor-count",
    "scope-enter-count",
    "sender-pid",
    "sender-uid",
    "signal",
    "signals",
    "spans",
    "spec",
    "stats",
    "term",
    "term-display",
    "term-kind",
    "term-span",
    "tier",
    "value",
    "x",
    // Usage keys (`subprocess/rusage`)
    "max-rss-kb",
    "sys-us",
    "user-us",
    // File metadata keys (`file/stat`, `file/lstat`)
    "accessed",
    "blksize",
    "created",
    "dev",
    "file-type",
    "gid",
    "inode",
    "is-dir",
    "is-file",
    "is-symlink",
    "modified",
    "nlinks",
    "permissions",
    "rdev",
    "readonly",
    "uid",
    // Compile-query and rewrite keys (`compile/signal`, `compile/bindings`,
    // `compile/call-graph`, `compile/diagnostics`, `compile/rename`)
    "bits",
    "callees",
    "callers",
    "captures",
    "edits",
    "immutable",
    "jit-eligible",
    "leaves",
    "lines",
    "mutated",
    "needs-lbox",
    "new-function",
    "nodes",
    "propagates",
    "roots",
    "rule",
    "safe",
    "scope",
    "severity",
    "shared-captures",
    "silent",
    "source",
    "suggestions",
    "tail",
    "usages",
    "wraps",
    "yields",
    // Status and outcome keywords
    "denied",
    "disconnected",
    "empty",
    "error",
    "failed",
    "flip",
    "full",
    "ineligible",
    "missing",
    "ok",
    "pending",
    "ready",
    "recursive",
    "gated",
    // Capability / feature gating
    "capability-denied",
    "feature-disabled",
    // Signal names the registry pre-registers. A signal a program declares at
    // run time cannot be listed here; it is learned where the registry is read
    // (docs/impl/symbol.md § "The display memo").
    "debug",
    "exec",
    "fs",
    "fuel",
    "io",
    "os-signal",
    "wait",
    "yield",
    // Error kinds (`ctx.error(kind, …)` and the VM's error constructors make
    // the `:error` field's keyword)
    "argument-error",
    "assertion-failed",
    "arity-error",
    "compile-error",
    "division-by-zero",
    "dns-error",
    "double-free",
    "encoding-error",
    "exec-error",
    "ffi-error",
    "fiber-error",
    "format-error",
    "internal-error",
    "io-error",
    "match-error",
    "mlir-error",
    "os-signal-error",
    "overflow-error",
    "range-error",
    "read-error",
    "rewrite-error",
    "runtime-error",
    "serde-error",
    "state-error",
    "task-error",
    "thread-error",
    "tier-rejected",
    "trait-error",
    "type-error",
    "unknown-tier",
    "allocation-error",
    "analysis-error",
    "barrier-error",
    "eval-error",
    "lookup-error",
    "parse-error",
    "signal-error",
    "syntax-error",
    "value-error",
    "stack-overflow",
    "out-of-fuel",
    "halt",
    "double-resume",
    "failed-assertion",
    "not-implemented",
    "timed-out",
    "exited",
    "signal-violation",
    "use-after-free",
    "wasm-error",
    // Type names (`type-of` and type errors mint `Value::keyword(type_name())`)
    "boolean",
    "float",
    "integer",
    "keyword",
    "list",
    "native-fn",
    "nil",
    "ptr",
    "symbol",
    "unknown",
    "array",
    "@array",
    "box",
    "bytes",
    "@bytes",
    "capture-cell",
    "closure",
    "closure-template",
    "external",
    "ffi",
    "ffi-signature",
    "ffi-type",
    "fiber",
    "library-handle",
    "parameter",
    "set",
    "@set",
    "string",
    "@string",
    "struct",
    "@struct",
    "subprocess",
    "syntax",
    "thread-handle",
    // External type names: the `ctx.external(type_name, …)` a primitive wraps
    // its handle in, which is what `type-of` hands back for that handle.
    // "port" and "subprocess" appear above; "process" is there as an ordinary
    // keyword, not as a type name — an OS child is a `subprocess` here, and
    // `process` means an Erlang-style process (docs/processes.md).
    "analysis",
    "chan/receiver",
    "chan/sender",
    "fs-watcher",
    "io-backend",
    "io-request",
    "signal-receiver",
    // Trait protocol keys
    "Collection",
    "Sequence",
    "conj",
    "display",
    "empty?",
    "has?",
    "iter",
    "nth",
    // Compile / VM / config keywords
    "compile/barrier-module",
    "compile/dumps",
    "compile/run-on",
    "compile/whole-module",
    "compile/whole-module-syntax",
    "debug-bytecode",
    "list-primitives",
    "primitive",
    "primitive-meta",
    "vm/config",
    "vm/config-set",
    "trace",
    "unicode",
    "max-depth",
    "home",
    "plugin-suffix",
    "adaptive",
    "custom",
    "eager",
    "lazy",
    "off",
    "on",
    // Execution tiers (`VM::active_tier`, reported by `(vm/tier)`)
    "bytecode",
    "git",
    "gpu",
    "jit",
    "jit?",
    "jit/rejections",
    "mlir",
    "mlir-cpu",
    "mlir/compile-spirv",
    "vm",
    "wasm",
    // Arena / memory gauges
    "arena/allocs",
    "arena/stats",
    "object-count",
    "object-limit",
    "objects",
    // I/O and process keywords
    "read-write",
    "timeout",
    "read",
    "write",
    "inherit",
    "null",
    "pipe",
    "async",
    "keys",
    "deny",
    "from",
    "start",
    "current",
    "end",
    "text",
    "binary",
    "keepalive",
    "encoding",
    "sigterm",
    "sigkill",
    "sighup",
    "sigint",
    "sigquit",
    "sigpipe",
    "sigalrm",
    "sigusr1",
    "sigusr2",
    "sigchld",
    "sigcont",
    "sigstop",
    "sigtstp",
    "sigttin",
    "sigttou",
    "sigwinch",
    "stderr",
    "stdin",
    "stdout",
    // File-watch event kinds
    "create",
    "modify",
    "remove",
    "rename",
    // FFI type keywords (`TypeDesc::from_keyword`; "float"/"string" appear
    // above)
    "bool",
    "char",
    "default",
    "double",
    "i16",
    "i32",
    "i64",
    "i8",
    "int",
    "long",
    "short",
    "size",
    "ssize",
    "u16",
    "u32",
    "u64",
    "u8",
    "uchar",
    "uint",
    "ulong",
    "ushort",
    "void",
    // Fiber statuses
    "alive",
    "dead",
    "new",
    "paused",
    // Introspection enums: binding scope, capture kind, diagnostic severity,
    // symbol kind, LIR terminator kind, compile-dump kind ("parameter",
    // "error", "jit" already appear above)
    "local",
    "lbox",
    "transitive",
    "info",
    "warning",
    "function",
    "variable",
    "builtin",
    "macro",
    "module",
    "branch",
    "emit",
    "jump",
    "return",
    "unreachable",
    "ast",
    "cfg",
    "defuse",
    "dfa",
    "escape",
    "fhir",
    "hir",
    "lir",
    "regions",
    // Trace keywords (`TRACE_KEYWORDS`, the keys of `(vm/config :trace)`) not
    // listed above
    "anf",
    "arena",
    "boot",
    "call",
    "capture",
    "census",
    "chan",
    "compile",
    "free",
    "freebt",
    "guardfree",
    "import",
    "pages",
    "park",
    "posix",
    "residue",
    "scrub",
    "spirv",
    "syncjit",
];
