// audited: 2026-10-06
//! A decoded instruction back in the working form, field for field, so a test compares what froze with what decodes.
//!
//! docs/impl/lir.md

use super::*;

fn thaw_const(c: ConstRef) -> LirConst {
    match c {
        ConstRef::Nil => LirConst::Nil,
        ConstRef::EmptyList => LirConst::EmptyList,
        ConstRef::Bool(b) => LirConst::Bool(b),
        ConstRef::Int(n) => LirConst::Int(n),
        ConstRef::Float(f) => LirConst::Float(f),
        ConstRef::Symbol(s) => LirConst::Symbol(s),
        ConstRef::Keyword(k) => LirConst::Keyword(k),
    }
}

/// A decoded instruction back in the working form, field for field.
pub(super) fn thaw(i: InstrRef<'_>) -> LirInstr {
    use InstrRef as R;
    use LirInstr as I;
    match i {
        R::Const { dst, value } => I::Const {
            dst,
            value: thaw_const(value),
        },
        R::ValueConst { dst, value } => I::ValueConst { dst, value },
        R::MaterializeConst {
            dst,
            template,
            region,
        } => I::MaterializeConst {
            dst,
            template: template.decode(),
            region,
        },
        R::LoadLocal { dst, slot } => I::LoadLocal { dst, slot },
        R::StoreLocal { slot, src } => I::StoreLocal { slot, src },
        R::StoreLocalRefcounted { slot, src } => I::StoreLocalRefcounted { slot, src },
        R::LoadCapture { dst, index } => I::LoadCapture { dst, index },
        R::LoadCaptureRaw { dst, index } => I::LoadCaptureRaw { dst, index },
        R::StoreCapture { index, src } => I::StoreCapture { index, src },
        R::MakeClosure {
            dst,
            closure_id,
            captures,
            region,
        } => I::MakeClosure {
            dst,
            closure_id,
            captures: captures.to_vec(),
            region,
        },
        R::LoadSelf { dst } => I::LoadSelf { dst },
        R::Call {
            dst,
            func,
            args,
            arity_checked,
            region,
        } => I::Call {
            dst,
            func,
            args: args.to_vec(),
            arity_checked,
            region,
        },
        R::SuspendingCall {
            dst,
            func,
            args,
            arity_checked,
            region,
        } => I::SuspendingCall {
            dst,
            func,
            args: args.to_vec(),
            arity_checked,
            region,
        },
        R::TailCall {
            dst,
            func,
            args,
            arity_checked,
            region,
            defer_callee_release,
            deferred_release_slot,
            borrowed_arg_slots,
        } => I::TailCall {
            dst,
            func,
            args: args.to_vec(),
            arity_checked,
            region,
            defer_callee_release,
            deferred_release_slot,
            borrowed_arg_slots: borrowed_arg_slots.iter().collect(),
        },
        R::List {
            dst,
            head,
            tail,
            region,
        } => I::List {
            dst,
            head,
            tail,
            region,
        },
        R::MakeArrayMut {
            dst,
            elements,
            region,
        } => I::MakeArrayMut {
            dst,
            elements: elements.to_vec(),
            region,
        },
        R::First { dst, pair } => I::First { dst, pair },
        R::Rest { dst, pair } => I::Rest { dst, pair },
        R::BinOp {
            dst,
            op,
            lhs,
            rhs,
            proof,
        } => I::binop_proved(dst, op, lhs, rhs, proof),
        R::UnaryOp {
            dst,
            op,
            src,
            proof,
        } => I::unary_proved(dst, op, src, proof),
        R::Convert { dst, op, src } => I::Convert { dst, op, src },
        R::Compare {
            dst,
            op,
            lhs,
            rhs,
            proof,
        } => I::compare_proved(dst, op, lhs, rhs, proof),
        R::IsNil { dst, src } => I::IsNil { dst, src },
        R::IsPair { dst, src } => I::IsPair { dst, src },
        R::IsArray { dst, src } => I::IsArray { dst, src },
        R::IsArrayMut { dst, src } => I::IsArrayMut { dst, src },
        R::IsStruct { dst, src } => I::IsStruct { dst, src },
        R::IsStructMut { dst, src } => I::IsStructMut { dst, src },
        R::IsSet { dst, src } => I::IsSet { dst, src },
        R::IsSetMut { dst, src } => I::IsSetMut { dst, src },
        R::ArrayMutLen { dst, src } => I::ArrayMutLen { dst, src },
        R::MakeCaptureCell {
            dst,
            value,
            region,
            name,
            mutated,
        } => I::MakeCaptureCell {
            dst,
            value,
            region,
            name,
            mutated,
        },
        R::LoadCaptureCell { dst, cell } => I::LoadCaptureCell { dst, cell },
        R::StoreCaptureCell { cell, value } => I::StoreCaptureCell { cell, value },
        R::MatchFail { dst, src } => I::MatchFail { dst, src },
        R::FirstDestructure { dst, src } => I::FirstDestructure { dst, src },
        R::RestDestructure { dst, src } => I::RestDestructure { dst, src },
        R::ArrayMutRefDestructure { dst, src, index } => {
            I::ArrayMutRefDestructure { dst, src, index }
        }
        R::ArrayMutSliceFrom { dst, src, index } => I::ArrayMutSliceFrom { dst, src, index },
        R::StructGetOrNil { dst, src, key } => I::StructGetOrNil {
            dst,
            src,
            key: thaw_const(key),
        },
        R::StructGetDestructure { dst, src, key } => I::StructGetDestructure {
            dst,
            src,
            key: thaw_const(key),
        },
        R::StructRest {
            dst,
            src,
            exclude_keys,
        } => I::StructRest {
            dst,
            src,
            exclude_keys: exclude_keys.iter().map(thaw_const).collect(),
        },
        R::FirstOrNil { dst, src } => I::FirstOrNil { dst, src },
        R::RestOrNil { dst, src } => I::RestOrNil { dst, src },
        R::ArrayMutRefOrNil { dst, src, index } => I::ArrayMutRefOrNil { dst, src, index },
        R::LoadResumeValue { dst } => I::LoadResumeValue { dst },
        R::Eval { dst, expr, env } => I::Eval { dst, expr, env },
        R::ArrayMutExtend { dst, array, source } => I::ArrayMutExtend { dst, array, source },
        R::ArrayMutPush { dst, array, value } => I::ArrayMutPush { dst, array, value },
        R::CallArrayMut {
            dst,
            func,
            args,
            region,
            args_region,
        } => I::CallArrayMut {
            dst,
            func,
            args,
            region,
            args_region,
        },
        R::TailCallArrayMut {
            func,
            args,
            region,
            args_region,
        } => I::TailCallArrayMut {
            func,
            args,
            region,
            args_region,
        },
        R::IncrefRegion { region_id } => I::IncrefRegion { region_id },
        R::DecrefRegion { region_id } => I::DecrefRegion { region_id },
        R::DecrefValueRegion { src } => I::DecrefValueRegion { src },
        R::DecrefCellRegion { src } => I::DecrefCellRegion { src },
        R::IncrefValueRegion { src } => I::IncrefValueRegion { src },
        R::AdoptRegion { parent, child } => I::AdoptRegion { parent, child },
        R::AdoptCellRegion { parent, child } => I::AdoptCellRegion { parent, child },
        R::FreeRegionGroup { members } => I::FreeRegionGroup {
            members: members.to_vec(),
        },
        R::AdoptIntoActivation { child } => I::AdoptIntoActivation { child },
        R::AssertRegionMatches { region_id, src } => I::AssertRegionMatches { region_id, src },
        R::PushParamFrame { pairs } => I::PushParamFrame {
            pairs: pairs.to_vec(),
        },
        R::PopParamFrame => I::PopParamFrame,
        R::CheckSignalBound { src, allowed_bits } => I::CheckSignalBound { src, allowed_bits },
        R::IsEmpty { dst, src } => I::IsEmpty { dst, src },
        R::IsBool { dst, src } => I::IsBool { dst, src },
        R::IsInt { dst, src } => I::IsInt { dst, src },
        R::IsFloat { dst, src } => I::IsFloat { dst, src },
        R::IsString { dst, src } => I::IsString { dst, src },
        R::IsKeyword { dst, src } => I::IsKeyword { dst, src },
        R::IsSymbolCheck { dst, src } => I::IsSymbolCheck { dst, src },
        R::IsBytes { dst, src } => I::IsBytes { dst, src },
        R::IsBox { dst, src } => I::IsBox { dst, src },
        R::IsClosure { dst, src } => I::IsClosure { dst, src },
        R::IsFiber { dst, src } => I::IsFiber { dst, src },
        R::TypeOf { dst, src } => I::TypeOf { dst, src },
        R::Length { dst, src } => I::Length { dst, src },
        R::Get { dst, obj, key } => I::Get { dst, obj, key },
        R::Put { dst, obj, key, val } => I::Put { dst, obj, key, val },
        R::Del { dst, obj, key } => I::Del { dst, obj, key },
        R::Has { dst, obj, key } => I::Has { dst, obj, key },
        R::IntrPush { dst, array, value } => I::IntrPush { dst, array, value },
        R::IntrStringPush { dst, string, value } => I::IntrStringPush { dst, string, value },
        R::IntrBytesPush { dst, bytes, value } => I::IntrBytesPush { dst, bytes, value },
        R::Pop { dst, src } => I::Pop { dst, src },
        R::Freeze { dst, src, region } => I::Freeze { dst, src, region },
        R::Thaw { dst, src, region } => I::Thaw { dst, src, region },
        R::Identical { dst, lhs, rhs } => I::Identical { dst, lhs, rhs },
    }
}
