(elle/epoch 13)
# audited: 2026-09-30
# The ledger of tests/impl/oracle.lisp, the region leak dashboard: one row per probe and axis, every control pinned at 0.
(producer "tests/impl/oracle.lisp")
# The instrument's live-growth row per gauge the oracle reads, and the
# estimator's own sub-integer self-test: growth floors, each voiding its axis
# when it reads flat.
["objects gauge (live-growth)" :objects :floor 0.5 :class :growth]
["ids gauge (live-growth)" :ids :floor 0.5 :class :growth]
["regions gauge (live-growth)" :regions :floor 0.5 :class :growth]
["bytes gauge (live-growth)" :bytes :floor 1000 :class :growth]
["sub-integer (1-in-3 retain)" :objects :floor 0.28 :class :growth]
["bounded (immutable struct, dropped)" :objects 0]
# The direct-loop rows (probe/direct.lisp).
["discard-struct" :objects 0]
["string-alloc" :objects 0]
["pair" :objects 0]
["let-struct" :objects 0]
["traited" :objects 0]
["closure-template" :objects 0]
["branch-one-arm" :objects 0]
["branch-fresh-arm" :objects 0]
["branch-nested" :objects 0]
["branch-error-arg" :objects 0]
["cmp-gt" :objects 0]
["cmp-lt" :objects 0]
["cmp-ge" :objects 0]
["fiber-drop" :objects 0]
["fiber-resume" :objects 0]
["fiber-deliver" :objects 0]
["array-literal" :objects 0]
["mut-array" :objects 0]
["mut-array-push" :objects 0 :root :f1b]
["mut-struct" :objects 0]
["mut-string" :objects 0 :root :f1b]
["nested-loop" :objects 0]
["reduce" :objects 0 :root :f1a]
["fold" :objects 0 :root :f1a]
["zip" :objects 0]
["sort" :objects 0]
["reverse" :objects 0]
["rest-array-copy" :objects 0]
["distinct" :objects 0]
["take" :objects 0]
["drop" :objects 0]
["group-by" :objects 0]
["frequencies" :objects 0]
["to-array" :objects 0]
["to-list" :objects 0]
["freeze" :objects 0]
["slice" :objects 0]
["keys-values" :objects 0]
["merge" :objects 0]
["struct-lit" :objects 0]
["struct-get" :objects 0]
["struct-put" :objects 0 :root :f1b]
["push-churn" :objects 0 :root :f1b]
["capture-backedge" :objects 0]
["returned-cycle" :objects 0]
["string-interp" :objects 0]
["concat" :objects 0]
["split" :objects 0]
["join" :objects 0]
["trim" :objects 0]
["replace" :objects 0]
["num-to-str" :objects 0]
["read" :objects 0]
["call-chain" :objects 0]
["arg-result" :objects 0]
["let-chain" :objects 0]
["each-array" :objects 0]
["each-manual" :objects 0]
["list-cursor" :objects 0]
["cell-alias-after" :objects 0]
["cell-arm-store" :objects 0]
["format" :objects 0]
["pipeline" :objects 0]
["each-list" :objects 0]
["map-while" :objects 0]
["filter-while" :objects 0]
["mapcat-while" :objects 0]
["nested-closure" :objects 0]
["user-struct" :objects 0]
["user-string" :objects 0]
["chain" :objects 0]
["wrap-map" :objects 0]
["factory" :objects 0]
["cond-factory" :objects 0]
["alias" :objects 0]
["nested-factory" :objects 0]
["struct-field" :objects 0]
["heap-struct-field" :objects 0]
["g-variant" :objects 0]
["bound-callee" :objects 0]
["break-skip" :objects 0]
["store-wrapper" :objects 0 :root :f1b]
["fresh-env-cell" :objects 0 :root :f5]
["env-cell-read-arm" :objects 0]
["shared-env-cell" :objects 0]
# The rows whose drive crosses a fiber (probe/concurrent.lisp). A park family
# is read on the region count too, the dimension a pages-less owner node or an
# emptied entry moves.
["closure-while" :objects 0]
["fiber-while" :objects 0]
["concat-while" :objects 0]
["protect-while" :objects 0 :root :f2]
["defer-while" :objects 0]
["defer-error" :objects 0]
["one-shot" :objects 0]
["alloc-return" :objects 0]
["fiber-nested" :objects 0 :root :f2]
["fiber-nested" :regions 0]
["multi-resume" :objects 0 :root :f2]
["multi-resume" :regions 0]
["protect-call" :objects 0]
["yield-discard" :objects 0 :root :f2]
["yield-discard" :regions 0]
["never-resumed" :objects 0]
["denied-discard" :objects 0 :root :f2]
["denied-discard" :regions 0 :root :f2]
["adopt-park-drop" :objects 0]
["adopt-park-drop" :regions 0]
["adopt-park-abort" :objects 0]
["adopt-park-abort" :regions 0]
["adopt-park-cancel" :objects 0]
["adopt-park-cancel" :regions 0]
["adopt-complete" :objects 0]
["adopt-complete" :regions 0]
["adopt-nopark" :objects 0]
["adopt-nopark" :regions 0]
["plain-park-drop" :objects 0]
["plain-park-drop" :regions 0]
["adopt-before-park-drop" :objects 0]
["adopt-before-park-drop" :regions 0]
["adopt-before-park-cancel" :objects 0]
["adopt-before-park-cancel" :regions 0]
["cancel-discard" :objects 0 :root :f2]
["cancel-discard" :regions 0]
["abort-discard" :objects 0]
["abort-discard" :regions 0]
["emit-dyn-discard" :objects 0]
["emit-dyn-tail" :objects 0]
["emit-lit-discard" :objects 0]
["emit-dyn-fresh" :objects 0]
["emit-dyn-tail-error" :objects 0]
["emit-dyn-error-discard" :objects 0]
["emit-lit-tail-error" :objects 0]
["emit-dyn-error-fresh" :objects 0]
["emit-dyn-error-repeat" :objects 0]
["emit-dyn-error-restart" :objects 0]
["emit-dyn-stmt-error-restart" :objects 0]
["emit-dyn-stmt-error-fresh" :objects 0]
["error-payload" :objects 0]
["error-payload-helper" :objects 0]
["error-payload-param" :objects 0]
["error-payload-struct" :objects 0]
["error-payload-native" :objects 0]
["primitive-resume-bind" :objects 0]
["primitive-resume-tail" :objects 0]
["primitive-resume-keep" :objects 0]
["emit-resume-literal" :objects 0]
["propagate-none" :objects 0]
["propagate-one" :objects 0]
["propagate-three" :objects 0]
["env-cell-def-capture" :objects 0]
["env-cell-let-twin" :objects 0]
["module-cell-read-window" :objects 0]
["module-cell-heap-init" :objects 0]
# Tail-call rotation, the letrec-local closures, and the scheduler round trip
# (probe/tailcall.lisp).
["recur-struct" :objects 0]
["recur-string" :objects 0]
["recur-mutual" :objects 0]
["recur-local-self" :objects 0]
["recur-local-mutual" :objects 0]
["recur-local-mutual-native" :objects 0]
["recur-local-mutual-op" :objects 0]
["recur-local-mutual-ret" :objects 0]
["recur-local-mutual-ret-foreign" :objects 0]
["recur-local-mutual-ret-value" :objects 0]
["recur-local-mutual-ret-bound" :objects 0]
["recur-local-mutual-factory" :objects 0]
["recur-local-defn-mutual" :objects 0]
["defn-module-factory" :objects 0]
["recur-local-self-mint" :objects 0]
["recur-local-foreign-mint" :objects 0]
["recur-local-self-yield" :objects 0]
["recur-local-self-send" :objects 0]
["spawn-join" :objects 0]
# The stdlib, native-tail and read/copy classes (probe/stdlib.lisp). The
# native-tail and read rows are read on the region count, the dimension a
# fresh-result region with few contents moves.
["stdlib-concat" :objects 0]
["stdlib-fold" :objects 0]
["zip-tower" :objects 0]
["native-tail-put-struct" :regions 0 :root :f1b]
["native-tail-put-array" :regions 0 :root :f1b]
["native-tail-del-ctl" :regions 0 :root :f1b]
["native-tail-push-array" :regions 0]
["native-tail-add-set" :regions 0]
["native-tail-push-string" :regions 0]
["native-tail-push-mut-bytes" :regions 0]
["native-tail-pop-mut-string" :regions 0]
["read-first" :regions 0]
["read-rest" :regions 0]
["read-last" :regions 0]
["read-get-array" :regions 0]
["read-get-struct" :regions 0]
["read-has-struct" :regions 0]
["read-length" :regions 0]
["read-toarray" :regions 0]
["read-tolist" :regions 0]
["read-keys" :regions 0]
["read-values" :regions 0]
["read-slice" :regions 0]
["discard-passthrough" :objects 0]
["discard-closure" :objects 0]
# The injected abort delivery (probe/abort.lisp).
["abort-masked" :objects 0]
["abort-escape" :objects 0]
["abort-caught" :objects 0]
["abort-own-error" :objects 0]
["abort-reraise" :objects 0]
["abort-defer" :objects 0]
["abort-held" :objects 0]
["abort-other" :objects 0]
["abort-aborting-frame" :objects 0]
["abort-tail-result" :objects 0]
["abort-tail-discarded" :objects 0]
["abort-mask-caught-literal" :objects 0]
["abort-mask-caught-bound" :objects 0]
["refuse-tail-result" :objects 0]
["refuse-tail-discarded" :objects 0]
# The physical-id dimension and the mutable-store funnel (probe/store.lisp).
["id-const-compare" :ids 0]
["id-immediate-result" :ids 0]
["id-borrowed-index" :ids 0]
["id-borrowed-element" :ids 0]
["id-fresh-result" :ids 0]
["box-rebind" :objects 0]
["set-add" :objects 0 :root :f1b]
["raw-pop" :objects 0]
["pop-wrapper" :objects 0 :root :f1b]
["del-wrapper" :objects 0 :root :f1b]
["set-del-wrapper" :objects 0 :root :f1b]
["raw-del" :objects 0 :root :f5]
["raw-del-immediate" :objects 0 :root :f5]
# Fiber-internal yielding loops and the channel round trip (probe/yield.lisp).
["yield-struct" :objects 0]
["yield-string" :objects 0]
["yield-closure" :objects 0]
["yield-concat" :objects 0]
["yield-put" :objects 0]
["yield-reassign" :objects 0]
["yield-multimut" :objects 0 :root :f2]
["yield-spawn" :objects 0]
["chan-send-recv" :objects 0]
# Persistent containers, the returned accumulator, the walk's element and the
# captured accumulator (probe/container.lisp).
["put-overwrite" :objects 0]
["set-array" :objects 0]
["put-struct" :objects 0]
["roster" :objects 0]
["put-outer" :objects 0]
["push-outer" :objects 0]
["push-accum" :objects 0]
["struct-outer" :objects 0]
["string-outer" :objects 0]
["append-outer" :objects 0]
["loop-acc-return" :objects 0]
["recur-acc-return" :objects 0]
["walk-feeder-return" :objects 0]
["walk-feeder-discard" :objects 0]
["capture-acc-letrec" :objects 0]
["capture-acc-while" :objects 0]
["thread-acc-param" :objects 0]
# Discarded call results, break escapes, the branch-arm window and the
# frame-exit rows (probe/branch.lisp).
["branch-call" :objects 0]
["push-slot-source" :objects 0]
["put-slot-source" :objects 0]
["set-add-slot-source" :objects 0]
["put-churn" :objects 0 :root :f1b]
["match-dead-arm" :objects 0]
["match-used-arm" :objects 0]
["param-used-arm" :objects 0]
["param-used-arm-if" :objects 0]
["arm-alias-inside" :objects 0]
["arm-seq-read" :objects 0]
["arm-loop-read" :objects 0]
["branch-arm-tailcall-sibling" :objects 0]
["branch-arm-return-captured" :objects 0]
["struct-match" :objects 0]
["tail-frame-exit-unused" :objects 0]
["tail-frame-exit-arms" :objects 0]
["tail-frame-exit-captured" :objects 0]
["tail-frame-exit-handback" :objects 0]
["tail-frame-exit-moved" :objects 0]
["tail-frame-exit-fwd-cell" :objects 0]
["tail-frame-exit-fwd-cell-ret" :objects 0]
["tail-frame-exit-fwd-cell-sib" :objects 0]
["tail-frame-exit-operand-value" :objects 0]
["tail-frame-exit-callee-member" :objects 0]
["tail-frame-exit-fold-driver" :objects 0]
["tail-frame-exit-or-arm" :objects 0]
["tail-frame-exit-and-arm" :objects 0]
["break-value" :objects 0]
["break-value-used" :objects 0]
["break-value-lit" :objects 0]
["break-skipped" :objects 0]
["break-skipped-nobreak" :objects 0]
# Thunk-run native results and the byte gauge (probe/native.lisp).
["import-result" :objects 0]
["allocs-result" :objects 0]
["string-bytes" :bytes 0]
# The double-release counter, read once after the last probe. The counter is
# monotonic from process start, so 0 covers the stdlib load ahead of every
# probe as well (docs/impl/region/diagnostics.md).
["over-free" :releases 0]
